interface jsonnet {
    jsonnet-make: func() -> u64;
    jsonnet-evaluate-snippet: func(vm: u64,file: string,code: string) -> string;
    jsonnet-evaluate-file: func(vm: u64,path: string) -> string;
    jsonnet-ext-string: func(vm: u64,key: string, value: string);
    jsonnet-destroy: func(vm: u64);
    jsonnet-register-func: func(vm: u64, func-name: string, args-num: u32);
}

interface jsonnet-func {
    jsonnet-call-native-func: func(func-name:string, func-args:string) -> string;
}
